### PR TITLE
[ui5-tooling-transpile] fix for loading replaceVersion

### LINKED ISSUE #1062: Error message when building UI project using ui5-tooling-transpile without devDependency @ui5/builder
**Describe the bug**

Using ui5-tooling-transpile as described in the readme will get you an error message during build:

```
info ProjectBuilder Preparing build for project com.sap.cap.fe.ts.sample
info ProjectBuilder   Target directory: ./dist
info ProjectBuilder Cleaning target directory...
info Project 1 of 1: ❯ Building application project com.sap.cap.fe.ts.sample...
info com.sap.cap.fe.ts.sample › Running task escapeNonAsciiCharacters...
info com.sap.cap.fe.ts.sample › Running task replaceCopyright...
info com.sap.cap.fe.ts.sample › Running task replaceVersion...
info com.sap.cap.fe.ts.sample › Running task ui5-tooling-transpile-task...
error builder:custom-task:ui5-tooling-transpile-task Failed to replace the version in the TypeScript files!
Reason: Error: Cannot find module '@ui5/builder/tasks/replaceVersion'
Require stack:
- <local path>cap-fe-ts-sample2\app\samples\node_modules\ui5-tooling-transpile\lib\task.js
info com.sap.cap.fe.ts.sample › Running task minify...
info com.sap.cap.fe.ts.sample › Running task enhanceManifest...
warn builder:processors:manifestEnhancer /resources/com/sap/cap/fe/ts/sample/manifest.json: Generated supported locales ('') for bundle 'i18n/i18n.properties' do not contain default fallback locale 'en'. Either provide a properties file for 'en' or configure another available fallbackLocale
warn builder:processors:manifestEnhancer /resources/com/sap/cap/fe/ts/sample/manifest.json: Generated supported locales ('') for bundle 'i18n/i18n.properties' do not contain default fallback locale 'en'. Either provide a properties file for 'en' or configure another available fallbackLocale
info com.sap.cap.fe.ts.sample › Running task generateFlexChangesBundle...
info com.sap.cap.fe.ts.sample › Running task generateComponentPreload...
info com.sap.cap.fe.ts.sample › Running task ui5-task-zipper...
info ProjectBuilder Build succeeded in 1.74 s
info ProjectBuilder Executing cleanup tasks...
```

This is because a devDependency to `@ui5/builder` seems to be needed that is nowhere mentioned in the documentation. As soon as the devDependency is added, the error is gone. Interesting enough that the actual `replaceVersion` task does not seem to use the builder as there's no error message from that task 🤷🏻 

**Expected behavior**
No error message when building UI

**Additional context**
```
"@ui5/cli": "4.0.0",
"ui5-tooling-transpile": "3.4.7",
```

### PR DESCRIPTION
**Pull request by devinea**
Fixes #1062 

and issues like the following:

```
> ui5 build --config=ui5.yaml --clean-dest --dest dist

info ProjectBuilder Preparing build for project zbasicrel
info ProjectBuilder   Target directory: dist
info ProjectBuilder Cleaning target directory...
info Project 1 of 1: ❯ Building application project zbasicrel...
info zbasicrel › Running task escapeNonAsciiCharacters...
info zbasicrel › Running task replaceCopyright...
info zbasicrel › Running task replaceVersion...
info zbasicrel › Running task ui5-tooling-transpile-task...
info builder:custom-task:ui5-tooling-transpile-task Create Babel configuration based on ui5.yaml configuration options...
info builder:custom-task:ui5-tooling-transpile-task Using browserslist configuration from ui5.yaml...
error builder:custom-task:ui5-tooling-transpile-task Failed to replace the version in the TypeScript files!
Reason: Error: Cannot find module '@ui5/builder/tasks/replaceVersion'
Require stack:
- C:\SAPDevelop\Java\zbasicrel\node_modules\ui5-tooling-transpile\lib\task.js
```

### CODE REVIEW

**Comment by devinea** [comment]
@petermuessig - Please review

**Comment by petermuessig** [comment]
@devinea - I'll check this afternoon and release if it fits

File: packages/ui5-tooling-transpile/lib/task.js [hunk 1]
```diff
@@ -74,12 +74,20 @@ module.exports = async function ({ log, workspace /*, dependencies*/, taskUtil,
...
 	try {
 		// dynamically require the replaceVersion task
 		// (using the absolute path to the module to avoid issues with the module resolution)
-		const replaceVersion = (await import(pathToFileURL(require.resolve("@ui5/builder/tasks/replaceVersion"))))
-			.default;
+		const replaceVersion = (
+			await import(
+				pathToFileURL(
+					require.resolve("@ui5/builder/tasks/replaceVersion", {
+						paths: [cwd, `node_modules${path.sep}@ui5${path.sep}cli`]
```
Comment (petermuessig) [inline packages/ui5-tooling-transpile/lib/task.js:86]: hmm, this hard-coded path is not optimal - the CLI isn't necessarily part of the `node_modules` of the project - it can also be installed globally. I think we need to resolve the ' @ui5/cli` beforehand.

Comment (petermuessig) [reply packages/ui5-tooling-transpile/lib/task.js:86]: Please do it like that: 

```js
		const replaceVersion = (
			await import(
				pathToFileURL(
					require.resolve("@ui5/builder/tasks/replaceVersion", {
						paths: [cwd, path.dirname(require.resolve("@ui5/cli/package.json"))]
					})
				)
			)
		).default;
```

this ensures that the `@ui5/cli` path is resolved either locally or globally, depending how it has been installed.

Comment (devinea) [reply packages/ui5-tooling-transpile/lib/task.js]: Thanks @petermuessig. Updated as suggested.

**Comment by petermuessig** [comment]
Commit message voter can be ignored for the patch set as I nevertheless do a squash and merge. Thanks for updating @devinea

**Comment by devinea** [comment]
Thanks @petermuessig
